routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::name('admin.')->middleware([])->group(function () {
    Route::resource('customers',\App\Http\Controllers\HomeController::class);
    Route::get('customers/{id}/destroy',[\App\Http\Controllers\HomeController::class,'destroy'])->name('customersDestroy');
    Route::get('customers/{id}/password',[\App\Http\Controllers\HomeController::class,'change'])->name('changePassword');
    Route::post('customers/{id}/password',[\App\Http\Controllers\HomeController::class,'changePassword'])->name('changePassword.post');

    Route::resource('carousels',\App\Http\Controllers\CarouselController::class);
    Route::get('carousels/{id}/destroy',[\App\Http\Controllers\CarouselController::class,'destroy'])->name('carouselsDestroy');

    Route::resource('link',\App\Http\Controllers\LinkController::class);
    Route::get('link/{id}/destroy',[\App\Http\Controllers\LinkController::class,'destroy'])->name('linkDestroy');

    Route::resource('promosi',\App\Http\Controllers\PromosiController::class);
    Route::get('promosi/{id}/destroy',[\App\Http\Controllers\PromosiController::class,'destroy'])->name('promosiDestroy');

    Route::resource('materi',\App\Http\Controllers\MateriController::class);
    Route::get('materi/{id}/destroy',[\App\Http\Controllers\MateriController::class,'destroy'])->name('materiDestroy');

    Route::resource('workshop',\App\Http\Controllers\WorkshopController::class);
    Route::get('workshop/{id}/destroy',[\App\Http\Controllers\WorkshopController::class,'destroy'])->name('workshopDestroy');

    Route::resource('notifikasi',\App\Http\Controllers\NotifikasiController::class);
    Route::get('notifikasi/{id}/destroy',[\App\Http\Controllers\NotifikasiController::class,'destroy'])->name('notifikasiDestroy');

    Route::resource('binomo',\App\Http\Controllers\BinomoController::class);
    Route::get('binomo/{id}/destroy',[\App\Http\Controllers\BinomoController::class,'destroy'])->name('binomoDestroy');

    Route::resource('signal',\App\Http\Controllers\SignalController::class);
    Route::get('signal/{id}/destroy',[\App\Http\Controllers\SignalController::class,'destroy'])->name('signalDestroy');

    Route::get('customer/{id}/img',[\App\Http\Controllers\Apiv1\ProfilController::class,'getImg'])->name('get.Img');
    Route::put('customer/{id}/img/',[\App\Http\Controllers\Apiv1\ProfilController::class,'img'])->name('img');

});

app/Models/Materi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Materi extends Model
{
    use HasFactory;

    public function categories(){
        return $this->belongsTo(Category::class,'category_id');
    }

}

app/Http/Controllers/Apiv1/MateriController.php
<?php

namespace App\Http\Controllers\Apiv1;

use App\Http\Controllers\Controller;
use App\Models\Materi;
use App\Models\Promosi;
use App\Models\Workshop;
use Illuminate\Http\Request;

class MateriController extends Controller
{
    public function materi(){
        $basics = Materi::whereCategoryId(1)->get();

        return response()->json($basics);
    }
    public function workshop(){
        $workshops = Workshop::all();
        return response()->json($workshops);
    }
    public function promosi(){
        $promosis = Promosi::all();
        return response()->json($promosis);
    }
    public function intermediate(){
        $intermediates = Materi::whereCategoryId(2)->get();
//        $materies = Materi::all();
        return response()->json($intermediates);
    }
    public function advance(){
        $advances = Materi::whereCategoryId(3)->get();

        return response()->json($advances);
    }
}

app/Http/Controllers/MateriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Carousel;
use App\Models\Category;
use App\Models\Link;
use App\Models\Materi;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class MateriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = Materi::all();
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<a href="materi/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.materiDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.content.materi.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Category::all();
        view()->share([
           'categories' => $data
        ]);
        return view('admin.content.materi.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Materi();
        $data->link = $request->link;
        $data->value = $request->value;
        $data->category_id = $request->category_id;

        $data->save();


        return redirect()->route('admin.materi.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Materi::find($id);
        $categories = Category::all();
        view()->share([
            'data' => $data,
            'categories' => $categories

        ]);
        return view('admin.content.materi.edit');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Materi::find($id);
        $data->link = $request->link;
        $data->value = $request->value;
        $data->category_id = $request->category_id;

        $data->save();

        return redirect()->route('admin.materi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Materi::find($id);

        $data->delete();
        return redirect()->route('admin.materi.index')->withSucsess('berhasil di delete');
    }
}

resources/views/admin/content/materi/add.blade.php
@extends('admin.app')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>materi</h1>
            </div>
            <div class="card">

                <div class="card-body">
                    <form action="{{route('admin.materi.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Link</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="link" id="link" class="form-control @error('title') is-invalid @enderror">
                                @error('link')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                            <div class="col-sm-12 col-md-7">
                                <select class="form-control select2" name="category_id">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Value</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="value" id="value" class="form-control @error('title') is-invalid @enderror">
                                @error('value')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary mr-1" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="section-body">
            </div>
        </section>
    </div>
@endsection

resources/views/admin/content/materi/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>materi</h1>

            </div>
            <div class="card">

                <div class="card-body">
                    <form action="{{route('admin.materi.update',$data->id)}}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Link</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="link" id="link" value="{{$data->link}}" class="form-control @error('title') is-invalid @enderror">
                                @error('link')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                            <div class="col-sm-12 col-md-7">
                                <select class="form-control select2" name="category_id">
                                    <option value="{{$data->id}}">{{$data->categories->name}}</option>
                                @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Value</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="value" id="value" value="{{$data->value}}" class="form-control @error('title') is-invalid @enderror">
                                @error('value')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary mr-1" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="section-body">
            </div>
        </section>
    </div>
@endsection

resources/views/admin/content/materi/index.blade.php
@extends('admin.app')

@section('content')

<div class="main-content">
        <section class="section">

            <div class="section-header">
                <h1>materi</h1>

            </div>
            <div class="card">
                <div class="card-header">
                    <h4><a href="{{route('admin.materi.create')}}" class="btn btn-primary">TAMBAH DATA</a> </h4>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="item">
                            <thead>
                            <tr>
                                <th>link</th>
                                <th>value</th>
                                <th>action</th>

                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </section>
    </div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#item').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{route('admin.materi.index')}}",
            },
            columns: [
                {
                    data: 'link',
                    name: 'link'
                },
                {
                    data: 'value',
                    name: 'value'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                },

            ]
        });
    });
</script>
@endsection