routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::name('admin.')->middleware([])->group(function () {
    Route::resource('customers',\App\Http\Controllers\HomeController::class);
    Route::get('customers/{id}/destroy',[\App\Http\Controllers\HomeController::class,'destroy'])->name('customersDestroy');
    Route::get('customers/{id}/password',[\App\Http\Controllers\HomeController::class,'change'])->name('changePassword');
    Route::post('customers/{id}/password',[\App\Http\Controllers\HomeController::class,'changePassword'])->name('changePassword.post');

    Route::resource('carousels',\App\Http\Controllers\CarouselController::class);
    Route::get('carousels/{id}/destroy',[\App\Http\Controllers\CarouselController::class,'destroy'])->name('carouselsDestroy');

    Route::resource('link',\App\Http\Controllers\LinkController::class);
    Route::get('link/{id}/destroy',[\App\Http\Controllers\LinkController::class,'destroy'])->name('linkDestroy');

    Route::resource('promosi',\App\Http\Controllers\PromosiController::class);
    Route::get('promosi/{id}/destroy',[\App\Http\Controllers\PromosiController::class,'destroy'])->name('promosiDestroy');

    Route::resource('materi',\App\Http\Controllers\MateriController::class);
    Route::get('materi/{id}/destroy',[\App\Http\Controllers\MateriController::class,'destroy'])->name('materiDestroy');

    Route::resource('workshop',\App\Http\Controllers\WorkshopController::class);
    Route::get('workshop/{id}/destroy',[\App\Http\Controllers\WorkshopController::class,'destroy'])->name('workshopDestroy');

    Route::resource('notifikasi',\App\Http\Controllers\NotifikasiController::class);
    Route::get('notifikasi/{id}/destroy',[\App\Http\Controllers\NotifikasiController::class,'destroy'])->name('notifikasiDestroy');

    Route::resource('binomo',\App\Http\Controllers\BinomoController::class);
    Route::get('binomo/{id}/destroy',[\App\Http\Controllers\BinomoController::class,'destroy'])->name('binomoDestroy');

    Route::resource('signal',\App\Http\Controllers\SignalController::class);
    Route::get('signal/{id}/destroy',[\App\Http\Controllers\SignalController::class,'destroy'])->name('signalDestroy');

    Route::get('customer/{id}/img',[\App\Http\Controllers\Apiv1\ProfilController::class,'getImg'])->name('get.Img');
    Route::put('customer/{id}/img/',[\App\Http\Controllers\Apiv1\ProfilController::class,'img'])->name('img');

});

app/Models/Signal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Signal extends Model
{
    use HasFactory;
}

app/Http/Controllers/Apiv1/SignalController.php
<?php

namespace App\Http\Controllers\Apiv1;

use App\Http\Controllers\Controller;
use App\Models\Signal;
use Illuminate\Http\Request;

class SignalController extends Controller
{
    public function signal(){
        $data = Signal::first();

        return response()->json($data);
    }
}

app/Http/Controllers/SignalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Signal;
use Illuminate\Http\Request;

class SignalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Signal::first();
        view()->share([
            'data' => $data
        ]);

        return view('admin.content.Signal.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.content.Signal.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Signal();
        $data->date = $request->date;
        $data->value = $request->value;

        $data->save();

        return redirect()->route('admin.signal.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Signal::find($id);
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.Signal.edit');


    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Signal::find($id);
        $data->date = $request->date;
        $data->value = $request->value;

        $data->save();

        return redirect()->route('admin.signal.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Signal::find($id);
        $data->delete();

        return redirect()->back();
    }
}

resources/views/admin/content/Signal/add.blade.php
@extends('admin.app')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Signal</h1>
            </div>
            <div class="card">

                <div class="card-body">
                    <form action="{{route('admin.signal.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="date" name="date" id="date" class="form-control @error('title') is-invalid @enderror">
                                @error('date')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Value</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="value" id="value" class="form-control @error('title') is-invalid @enderror">
                                @error('value')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary mr-1" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="section-body">
            </div>
        </section>
    </div>
@endsection

resources/views/admin/content/Signal/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Signal</h1>

            </div>
            <div class="card">

                <div class="card-body">
                    <form action="{{route('admin.signal.update',$data->id)}}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="date" name="date" value="{{$data->date}}" id="date" class="form-control @error('title') is-invalid @enderror">
                                @error('date')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Value</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="value" id="value" value="{{$data->value}}"  class="form-control @error('title') is-invalid @enderror">
                                @error('value')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary mr-1" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="section-body">
            </div>
        </section>
    </div>
@endsection

resources/views/admin/content/Signal/index.blade.php
@extends('admin.app')

@section('content')

<div class="main-content">
        <section class="section">

            <div class="section-header">
                <h1>Link</h1>

            </div>
            <div class="card">
                <div class="card-header">
                    <h4><a href="{{route('admin.signal.create')}}" class="btn btn-primary">TAMBAH DATA</a> </h4>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="item">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Link</th>
                                <th>action</th>

                            </tr>
                            </thead>
                            <tbody>
                            @if($data == null)
                                <tr>
                                    <td>data kosong</td>
                                </tr>
                            @else
                                <tr>
                                    <td>{{$data->date}}</td>
                                    <td>{{$data->value}}</td>
                                    <td>
                                        <a href="{{route('admin.signal.edit',$data->id)}}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                                        <a  href="{{route('admin.signalDestroy',$data->id)}}" class="btn btn-danger" onclick="return confirm(`Are you sure?`)"><i class="fa fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </section>
    </div>

@endsection